exclude: [bootstrap, CNAME, Gemfile, Gemfile.lock, Makefile, README.md, .travis.yml, vendor]
permalink: /blog/:year/:month/:day/:title
paginate: 10
paginate_path: /blog/page:num
markdown: kramdown
gems: [jekyll-paginate]
